apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-secrets-sa
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-secrets-create
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-secrets-create-global
subjects:
- kind: ServiceAccount
  name: operator-secrets-sa
  namespace: demo
roleRef:
  kind: ClusterRole
  name: operator-secrets-create
  apiGroup: rbac.authorization.k8s.io